This PR adds the following:
jtaleric/k8s-netperf pull request #46
Opened 2023-03-24 22:04 UTC by krishvoor

1) Updates the Makefile targets
2) Refactor the Dockerfile

2023-03-25 00:42 UTC, jtaleric approved these changes
lgtm! Thanks @krishvoor!!

2023-03-25 01:13 UTC, jtaleric requested changes
Hit an issue running locally.

2023-03-25 01:13 UTC, jtaleric commented on containers/Dockerfile
> +RUN git reset --hard 3bc455b23f901dae377ca0a558e1e32aa56b31c4 && \
I tried this locally, and I am hitting : 

```
/bin/sh: line 10: makeinfo: command not found
make[3]: *** [Makefile:402: netperf.info] Error 127
make[3]: Leaving directory '/netperf/doc'
make[2]: Leaving directory '/netperf/doc'
make[2]: *** [Makefile:589: all-recursive] Error 1
make[1]: Leaving directory '/netperf'
make[1]: *** [Makefile:396: all-recursive] Error 1
make: *** [Makefile:335: all] Error 2
Error: building at STEP "RUN git reset --hard 3bc455b23f901dae377ca0a558e1e32aa56b31c4 &&     curl -O https://gist.githubusercontent.com/jtaleric/c367e06b9e3f782c042667577aa1f705/raw/71e9ed086d4c2aef24c7fce7f3d9b594873e621c/netperf.diff  &&     git apply netperf.diff &&     ./autogen.sh &&     ./configure --enable-sctp=yes --enable-demo=yes && make && make install": while running runtime: exit status 2
make: *** [Makefile:24: docker-build] Error 2

```
Seems like attempting to do this in one RUN command might be causing this, as the steps look right...

2023-03-27 08:12 UTC, krishvoor commented on containers/Dockerfile
> +RUN git reset --hard 3bc455b23f901dae377ca0a558e1e32aa56b31c4 && \
Looks like this is missing a package, texinfo.
Will update the Dockerfile and get back.

2023-03-28 12:29 UTC, jtaleric commented on patches/netperf.diff
> +diff --git a/src/nettest_omni.c b/src/nettest_omni.c
Lets store this in the container file, honestly I wanted to keep this patch out of this repo.

2023-03-28 12:29 UTC, jtaleric commented on patches/netperf.diff
> +diff --git a/src/nettest_omni.c b/src/nettest_omni.c
thoughts @krishvoor -- do we need to track this file here?

2023-03-28 12:33 UTC, krishvoor commented on patches/netperf.diff
> +diff --git a/src/nettest_omni.c b/src/nettest_omni.c
>thoughts @krishvoor -- do we need to track this file here?

This would keep everything in a "single" place instead, rather than scattered.

2023-03-28 23:27 UTC, jtaleric commented on patches/netperf.diff
> +diff --git a/src/nettest_omni.c b/src/nettest_omni.c
agreed if it was a regular changing file, but it is pretty static.. Either way, I am fine to keep it in the `containers/` directory. Just wanted to understand the want to warehouse it here.

2023-03-29 14:15 UTC, krishvoor commented on patches/netperf.diff
> +diff --git a/src/nettest_omni.c b/src/nettest_omni.c
Done, updated.

2023-03-29 15:08 UTC, krishvoor commented
Logs for more info:
[k8s-netperf.log](https://github.com/jtaleric/k8s-netperf/files/11102389/k8s-netperf.log)

2023-03-29 17:49 UTC, jtaleric approved these changes
lgtm

2023-03-29 20:02 UTC, merged