Update the Golang-lint ci
jtaleric/k8s-netperf pull request #47
Opened 2023-03-28 15:37 UTC by krishvoor

This PR updates the Golang-lint ci based on
https://golangci-lint.run/usage/install#github-actions

Highlights lint issues during failures

2023-03-28 15:49 UTC, krishvoor commented
Hey @jtaleric ptal

2023-03-28 23:34 UTC, jtaleric commented
:D Maybe we need to address these ;) 

![image](https://user-images.githubusercontent.com/3965163/228389900-97e3921a-eac1-45f4-ae70-6a8962d9b3ad.png)

2023-03-29 17:52 UTC, krishvoor commented
Some of the [static](https://staticcheck.io/docs/checks/ ) checks can be ignored:
Working on others Go-Lint warning(s)

2023-04-04 18:02 UTC, krishvoor commented
One last to go...

```
[build: pkg/results/result.go#L171](https://github.com/jtaleric/k8s-netperf/pull/47/files#annotation_10271105418)
SA1019: strings.Title has been deprecated since Go 1.18 and an alternative has been available since Go 1.0: The rule Title uses for word boundaries does not handle Unicode punctuation properly. Use golang.org/x/text/cases instead.  (staticcheck)
```

2023-04-05 07:25 UTC, krishvoor commented
Hi @jtaleric 👋 , ptal

2023-04-06 15:55 UTC, krishvoor commented
Hi @vishnuchalla 👋  ptal

2023-04-06 16:00 UTC, vishnuchalla commented
Code changes look good to me. But I think this branch still has some conflicts to be resolved with main. Thanks

2023-04-06 16:27 UTC, krishvoor commented
@vishnuchalla rebase done, ptal!

2023-04-06 16:28 UTC, vishnuchalla approved these changes

2023-04-10 10:30 UTC, krishvoor commented
Hi @vishnuchalla 👋 
To enforce new-workflow checks for other PRs, can we merge this?

2023-04-10 13:56 UTC, krishvoor commented
Hi @rsevilla87 👋 ptal

2023-04-10 17:10 UTC, rsevilla87 commented on pkg/archive/archive.go
> +		return fmt.Errorf(" Failed to open pod cpu archive file ")
Why are you adding spaces surrounding the Errorf arguments?, IIRC, the exceptions should be in lowercase.

2023-04-10 17:11 UTC, rsevilla87 commented on pkg/archive/archive.go
> +		defer podfp.Close()
The else statement is not needed here

2023-04-10 17:11 UTC, rsevilla87 commented on pkg/archive/archive.go
> +	} else {
The else statement is not needed here

2023-04-10 17:11 UTC, rsevilla87 commented on pkg/archive/archive.go
> +	} else {
The else statement is not needed here

2023-04-10 17:32 UTC, rsevilla87 commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
Using context.Background and not using it is similar here

2023-04-10 17:35 UTC, rsevilla87 commented on pkg/netperf/netperf.go
>  			"-m", fmt.Sprintf("%d", nc.MessageSize),
You can improve this statement too
```suggestion
			"-m", fmt.Sprint(nc.MessageSize),
```

2023-04-11 10:52 UTC, krishvoor commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
exec.Stream is deprecated, which leads to resource leaks. So replaced with StreamWithContext

>Using context.Background and not using a context at all is similar here

Right, without context.Background(), golangci-lint calls it as
```
krvoora-mac:k8s-netperf krvoora$ golangci-lint run pkg/iperf/*
pkg/iperf/iperf.go:120:3: not enough arguments in call to exec.StreamWithContext
        have (remotecommand.StreamOptions)
        want (context.Context, remotecommand.StreamOptions) (typecheck)
        })
         ^
krvoora-mac:k8s-netperf krvoora$
```

2023-04-11 11:28 UTC, krishvoor commented on pkg/archive/archive.go
> +		return fmt.Errorf(" Failed to open pod cpu archive file ")
Updated

2023-04-11 11:28 UTC, krishvoor commented on pkg/archive/archive.go
> +		defer podfp.Close()
Updated

2023-04-11 11:28 UTC, krishvoor commented on pkg/archive/archive.go
> +	} else {
Updated

2023-04-11 11:28 UTC, krishvoor commented on pkg/archive/archive.go
> +	} else {
Updated

2023-04-11 11:28 UTC, krishvoor commented on pkg/netperf/netperf.go
>  			"-m", fmt.Sprintf("%d", nc.MessageSize),
Updated

2023-04-11 19:34 UTC, rsevilla87 commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
sure, but you can use the original `exec.Stream()` method

2023-04-12 12:38 UTC, krishvoor commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
>sure, but you can use the original exec.Stream() method, there's no need to use StreamWithContext since you're using a dummy context

I hear you and I totally agree, if I use the original `exec.Stream()`, I will have to suppress the below warning/error

```
SA1019: exec.Stream is deprecated: use StreamWithContext instead to avoid possible
resource leaks. See https://github.com/kubernetes/kubernetes/pull/103177 for details.
```

2023-04-12 13:41 UTC, rsevilla87 commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
oh, I wasn't aware of such deprecation msg, let's keep StreamWithContext then

2023-04-12 13:41 UTC, rsevilla87 approved these changes
lgtm!

2023-04-12 13:58 UTC, chentex requested changes
Added some comments

2023-04-12 13:58 UTC, chentex commented on vendor/golang.org/x/text/cases/cases.go
Any reason why are we adding all this vendor files?

2023-04-12 14:09 UTC, krishvoor commented on pkg/metrics/system.go
> +				logging.Error(" Cannot unmarshal node information ")
good catch will update to keep this consistent across all...

2023-04-12 14:25 UTC, krishvoor commented on pkg/metrics/system.go
> +				logging.Error(" Cannot unmarshal node information ")
Updated.

2023-04-12 15:41 UTC, krishvoor commented on vendor/golang.org/x/text/cases/cases.go
In our recent f2f conversations, having "vendor" files in place helps in efficient compiling.
On the contrary, we can skip it from the source repo and resolve them locally and pull them before a fresh build.

2023-04-12 16:07 UTC, vishnuchalla commented on vendor/golang.org/x/text/cases/cases.go
Yes. IMHO, I think we should deal with building/compiling/resolving  vendor files in local and avoid pushing them to the git repository. None of the trending GO repos do that: https://github.com/trending/go. And if a repo disappears, then we should assume that it is not meant to be used and migrate to an equivalent alternative option. And also for this repo since we have releases enabled and executable binaries for each release, we need not worry much about vendor files, since we always have a previous stable binary version available if something breaks in a new release.

2023-04-13 16:52 UTC, vishnuchalla commented on vendor/golang.org/x/text/cases/cases.go
Here are some observations about vendor files. Its not taking too much time to build with in GitHub actions.
With vendor files: https://github.com/cloud-bulldozer/kube-burner/actions/runs/4691311776/jobs/8315613830?pr=289
Without vendor files: https://github.com/cloud-bulldozer/kube-burner/actions/runs/4691711670/jobs/8316520055
Its just a 20-30 seconds gap. I think we can leave vendor files to github actions. Let me know your thoughts on this. Thank you

2023-04-26 16:41 UTC, jtaleric approved these changes
lgtm, testing locally.

2023-04-26 16:44 UTC, krishvoor commented on pkg/iperf/iperf.go
> +	err = exec.StreamWithContext(context.Background(), remotecommand.StreamOptions{
Sticking with `StreamWithContext`

2023-04-26 17:56 UTC, jtaleric requested changes
Hit this issue locally - still reviewing.

2023-04-26 17:56 UTC, jtaleric commented on pkg/k8s/kubernetes.go
> +		Command:     []string{"/bin/bash", "-c", "netserver && iperf3 -s -p %d && sleep 10000000", "IperfServerCtlPort"},
This is incorrect. IperfServerCtlPort is a var not a string.

2023-04-26 17:56 UTC, jtaleric commented on pkg/k8s/kubernetes.go
> +		Command:   []string{"/bin/bash", "-c", "netserver && iperf3 -s -p %d && sleep 10000000", "IperfServerCtlPort"},
Same as the above.

2023-04-26 19:11 UTC, krishvoor commented on pkg/k8s/kubernetes.go
> +		Command:   []string{"/bin/bash", "-c", "netserver && iperf3 -s -p %d && sleep 10000000", "IperfServerCtlPort"},
Ack, updated, ptal.

2023-04-26 19:11 UTC, krishvoor commented on pkg/k8s/kubernetes.go
> +		Command:     []string{"/bin/bash", "-c", "netserver && iperf3 -s -p %d && sleep 10000000", "IperfServerCtlPort"},
Updated, ptal.

2023-04-27 01:33 UTC, jtaleric approved these changes
tesetd, lgmt!

2023-04-27 01:33 UTC, merged