Suggesting patches on restructuring the code
jtaleric/k8s-netperf pull request #50
Opened 2023-03-31 19:13 UTC by vishnuchalla

#### Description
Suggesting patches on top of the existing code.

#### Testing
Tested with `CLI`. Verified both `stdout` and `csv` results.

2023-04-03 20:32 UTC, jtaleric requested changes
This patchset seems out of sync with main.

2023-04-03 20:32 UTC, jtaleric commented on pkg/results/result.go
> +func initTable(header []string) (*tablewriter.Table) {
Possible bad rebase?

2023-04-04 12:13 UTC, vishnuchalla commented on pkg/archive/archive.go
> +func commonCsvHeaderFields() []string {
Added Driver field and rebased on top of main. Thanks!

2023-04-05 19:28 UTC, jtaleric commented
So, testing this patch i see 
```shell
15:26 $ cat result-1680716211.csv
Driver,Profile,Same node,Host Network,Service,Duration,Parallelism,# of Samples,Message Size,Avg Throughput,Throughput Metric,99%tile Observed Latency,Latency Metric
netperf,TCP_STREAM,false,false,false,10,1,3,1024,4923.653333,Mb/s,4,usec
iperf3,TCP_STREAM,false,false,false,10,1,3,1024,3111.568725,Mb/s,0,usec
netperf,TCP_STREAM,false,false,false,10,2,3,1024,9235.816667,Mb/s,9,usec
iperf3,TCP_STREAM,false,false,false,10,2,3,1024,3828.860501,Mb/s,0,usec
netperf,TCP_RR,false,false,false,10,2,3,1024,9846.400000,OP/s,244.66666666666666,usec
,,false,false,false,0,0,0,0,NaN,,NaN,usec
```

using 
```shell
15:27 $ cat test.yaml 
---
TCPStream:
   parallelism: 1
   profile: "TCP_STREAM"
   duration: 10
   samples: 3
   messagesize: 1024

TCPStreami2:
   parallelism: 2
   profile: "TCP_STREAM"
   duration: 10
   samples: 3
   messagesize: 1024

TCPRR2:
   parallelism: 2
   profile: "TCP_RR"
   duration: 10
   samples: 3
   messagesize: 1024
```

This might have been a problem with the introduction of iperf.

2023-04-05 23:59 UTC, vishnuchalla commented
> > So, testing this patch i see
> > ```shell
> > 15:26 $ cat result-1680716211.csv
> > Driver,Profile,Same node,Host Network,Service,Duration,Parallelism,# of Samples,Message Size,Avg Throughput,Throughput Metric,99%tile Observed Latency,Latency Metric
> > netperf,TCP_STREAM,false,false,false,10,1,3,1024,4923.653333,Mb/s,4,usec
> > iperf3,TCP_STREAM,false,false,false,10,1,3,1024,3111.568725,Mb/s,0,usec
> > netperf,TCP_STREAM,false,false,false,10,2,3,1024,9235.816667,Mb/s,9,usec
> > iperf3,TCP_STREAM,false,false,false,10,2,3,1024,3828.860501,Mb/s,0,usec
> > netperf,TCP_RR,false,false,false,10,2,3,1024,9846.400000,OP/s,244.66666666666666,usec
> > ,,false,false,false,0,0,0,0,NaN,,NaN,usec
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > using
> > ```shell
> > 15:27 $ cat test.yaml 
> > ---
> > TCPStream:
> >    parallelism: 1
> >    profile: "TCP_STREAM"
> >    duration: 10
> >    samples: 3
> >    messagesize: 1024
> > 
> > TCPStreami2:
> >    parallelism: 2
> >    profile: "TCP_STREAM"
> >    duration: 10
> >    samples: 3
> >    messagesize: 1024
> > 
> > TCPRR2:
> >    parallelism: 2
> >    profile: "TCP_RR"
> >    duration: 10
> >    samples: 3
> >    messagesize: 1024
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This might have been a problem with the introduction of iperf.
> 
> This patch did not introduce this issue, but I am wondering if we can fix this issue in this patchset, since it is making changes to the `archive` package.
> 
> https://github.com/jtaleric/k8s-netperf/blob/main/pkg/archive/archive.go#L291 in this loop, we need to check if https://github.com/jtaleric/k8s-netperf/blob/main/pkg/archive/archive.go#L296 `profile` contains "RR" and driver is iperf3, we just need to conintue.

I don't think that would be the correct check. Because when I log and see the row we are getting empty strings in case of those incorrect rows being written into csv. 

```
%v {{0 0  0 0 false }   false false { } { } {0 0 0  } 0001-01-01 00:00:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC false [] [] {0 0 0 0 0 0 0 0} {0 0 0 0 0 0 0 0} {[]} {[]}}
,,false,false,false,0,0,0,0,NaN,,NaN,usec
```

I think we might have to check for row.Profile/row.Driver with empty string values and eliminate those rows or else populate them with the data which you are expecting. Let me know your thoughts on this. Thanks!

2023-04-06 01:27 UTC, jtaleric commented
Addressing the above comments in #61

2023-04-06 01:31 UTC, jtaleric approved these changes
lgtm!

2023-04-06 01:33 UTC, merged